services:
  transformer:
    container_name: transformer
    build:
      context: .
      dockerfile: Dockerfile.arm64
    volumes:
      - ./app:/src/
    ports:
      - "6000:6000"
    shm_size: "2gb"
    tty: true
    stdin_open: true
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY:-}
      - TRANSFORMER_GLOBAL_DEVICE=cpu
    command: /bin/bash
