services:
  transformer:
    container_name: transformer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/src/
    ports:
      - "6000:6000"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    shm_size: "256mb"
    tty: true
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
